version: '3'
services:
    apache:
        build: .docker/apache
        container_name: udemy_apache
        ports:
        - 80:80
        volumes:
        - .docker/config/vhosts:/etc/apache2/sites-enabled
        - .:/home/wwwroot
        depends_on:
        - php

    mysql:
        image: mysql:5.7
        container_name: udemysymfony-mysql
        working_dir: /application
        volumes:
        - .docker/data/:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=udemysymfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=symfony
        ports:
        - "3306:3306"

    php:
        build: .docker/php
        container_name: udemy_php
        volumes:
        - .:/home/wwwroot
        environment:
        - maildev_host=udemy_maildev
        depends_on:
        - maildev
        - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: udemy_maildev
        ports:
        - 8001:80

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: sf4_phpmyadmin
#        environment:
#          PMA_HOST: mysql
#          PMA_PORT: 3306
#        ports:
#            - 8080:80
#        links:
#            - mysql

#    memcached:
#      image: memcached:alpine
#      container_name: vaicomatocha-memcached

#    redis:
#        image: redis:alpine
#        container_name: vaicomatocha-redis

#    elasticsearch:
#      image: elasticsearch:5.4-alpine
#      container_name: vaicomatocha-elasticsearch